# Generated by Django 3.2.5 on 2021-07-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=0, unique=True)),
                ('hash', models.CharField(max_length=200, verbose_name='Хэш блока')),
                ('timestamp', models.IntegerField(default=0)),
                ('miner', models.CharField(max_length=200, verbose_name='Адрес майнера')),
                ('transactionCount', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
    ]
